# Generated by Django 3.1.6 on 2021-02-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictword', '0002_auto_20210208_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictword',
            name='partOfSpeech',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
