# Generated by Django 3.1.6 on 2021-02-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictword', '0003_dictword_partofspeech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictword',
            name='definition',
            field=models.TextField(),
        ),
    ]
