# Generated by Django 3.1.6 on 2021-02-08 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictword', '0004_auto_20210208_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictword',
            name='user',
        ),
        migrations.AddField(
            model_name='dictword',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
