# Generated by Django 3.1.6 on 2021-02-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictword', '0007_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='points',
        ),
    ]
