# Generated by Django 3.1.6 on 2021-02-09 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictword', '0008_auto_20210209_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictword',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
