# Generated by Django 3.1.6 on 2021-02-09 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictword', '0009_auto_20210209_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictword',
            name='definition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dictword',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
