# Generated by Django 3.1.6 on 2021-02-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictword', '0011_auto_20210209_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='appear_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
